//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IRestService")]
public interface IRestService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/XMLData", ReplyAction="http://tempuri.org/IRestService/XMLDataResponse")]
    string XMLData(string id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/XMLData", ReplyAction="http://tempuri.org/IRestService/XMLDataResponse")]
    System.Threading.Tasks.Task<string> XMLDataAsync(string id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/JSONData", ReplyAction="http://tempuri.org/IRestService/JSONDataResponse")]
    string JSONData(string id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/JSONData", ReplyAction="http://tempuri.org/IRestService/JSONDataResponse")]
    System.Threading.Tasks.Task<string> JSONDataAsync(string id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/sayHelloTo", ReplyAction="http://tempuri.org/IRestService/sayHelloToResponse")]
    string sayHelloTo(string name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/sayHelloTo", ReplyAction="http://tempuri.org/IRestService/sayHelloToResponse")]
    System.Threading.Tasks.Task<string> sayHelloToAsync(string name);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IRestServiceChannel : IRestService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class RestServiceClient : System.ServiceModel.ClientBase<IRestService>, IRestService
{
    
    public RestServiceClient()
    {
    }
    
    public RestServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public RestServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RestServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string XMLData(string id)
    {
        return base.Channel.XMLData(id);
    }
    
    public System.Threading.Tasks.Task<string> XMLDataAsync(string id)
    {
        return base.Channel.XMLDataAsync(id);
    }
    
    public string JSONData(string id)
    {
        return base.Channel.JSONData(id);
    }
    
    public System.Threading.Tasks.Task<string> JSONDataAsync(string id)
    {
        return base.Channel.JSONDataAsync(id);
    }
    
    public string sayHelloTo(string name)
    {
        return base.Channel.sayHelloTo(name);
    }
    
    public System.Threading.Tasks.Task<string> sayHelloToAsync(string name)
    {
        return base.Channel.sayHelloToAsync(name);
    }
}
